### ISSUE TITLE
`v0.2.0` checklist

### ISSUE THREAD

**Issue by rustaceanrob** [rustaceanrob/kyoto#140]
- [x] `BlockQueue::received` needs work
- [x] Validate block merkle root
- [x] Update contributing with module descriptions
- [x] Add header checkpoints
- [x] Bump `toml` to `v0.2.0`
