### ISSUE TITLE
0.1 Tracking Issue

### ISSUE THREAD

**Issue by rustaceanrob** [rustaceanrob/kyoto#79]
- [x] Chain struct testing
- [x] Sync in CI
- [x] Remove old blocks from `BlockQueue`
- [x] Clean up any unnecessary `expect` or `unwrap`
- [x] Add header checkpoints
- [x] Update documentation
- [x] Avoid `clone` when parsing `Block`
